name: "CLA"
on:
    issue_comment:
        types: [created]
    pull_request_target:
        types: [opened, closed, synchronize]

permissions:
    actions: write
    contents: write
    pull-requests: write
    statuses: write

jobs:
    default:
        runs-on: ubuntu-latest
        steps:
            - name: "CLA Assistant"
              if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
              uses: contributor-assistant/github-action@v2.5.2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  path-to-signatures: '.cla/signatures.json'
                  path-to-document: 'https://gist.github.com/tada5hi/0777b868a51c7a6e4080b9d1b19c8192'
                  allowlist: tada5hi,bot*
                  create-file-commit-message: "chore: created CLA file for storing signatures"
                  signed-commit-message: "$contributorName signed the CLA"
                  lock-pullrequest-aftermerge: false
