name: docker

on:
    push:
        branches:
            - master
        tags:
            - v*

jobs:
    push:
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read

        steps:
            -   uses: actions/checkout@v3

            -   uses: tada5hi/action-docker-image-publish@master
                if: github.ref_type == 'tag'
                with:
                    cache: true
                    registryRepository: authup-server
                    registryTag: latest

            -   uses: tada5hi/action-docker-image-publish@master
                if: github.ref_type == 'tag'
                with:
                    registryProject: tada5hi
                    registryRepository: authup
                    registryUser: tada5hi
                    registryTag: next
                    registryPassword: ${{ secrets.DOCKER_HUB_TOKEN }}

            -   uses: tada5hi/action-docker-image-publish@master
                if: github.ref_type == 'branch'
                with:
                    registryRepository: authup-server
                    registryTag: next

            -   uses: tada5hi/action-docker-image-publish@master
                if: github.ref_type == 'branch'
                with:
                    cache: true
                    registryProject: tada5hi
                    registryRepository: authup
                    registryUser: tada5hi
                    registryTag: next
                    registryPassword: ${{ secrets.DOCKER_HUB_TOKEN }}


