name: docker

on:
    push:
        branches:
            - master
        tags:
            - v*

jobs:
    push:
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read

        steps:
            -   uses: actions/checkout@v3

            -   uses: tada5hi/action-docker-image-publish@master
                with:
                    cache: true
                    registryRepository: authup-server
                    registryTag: ${{ github.ref_type == 'tag' && 'latest' || 'next' }}

            -   uses: tada5hi/action-docker-image-publish@master
                with:
                    registryHost: docker.io
                    registryProject: tada5hi
                    registryRepository: authup-server
                    registryUser: tada5hi
                    registryTag: ${{ github.ref_type == 'tag' && 'latest' || 'next' }}
                    registryPassword: ${{ secrets.DOCKER_HUB_TOKEN }}


