name: Docs

on:
    push:
        branches:
            - master

env:
    PRIMARY_NODE_VERSION: 18

jobs:
    install:
        name: Checkout and Install
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install
              uses: ./.github/actions/install
              with:
                  node-version: ${{ env.PRIMARY_NODE_VERSION }}

            - name: Build
              run: npm run docs:build

            - name: CNAME
              run: |
                    cd ./docs/.vitepress/dist/
                    touch CNAME
                    echo "authelion.net" > CNAME

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./docs/.vitepress/dist
