name: Release

on:
    push:
        branches:
            - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
    NODE_VERSION: 18

permissions:
    packages: write
    contents: write
    pull-requests: write

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest

        steps:
            -   uses: google-github-actions/release-please-action@v4
                id: release
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}

            -   name: Checkout
                if: ${{ steps.release.outputs.releases_created }}
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            -   name: Install
                if: ${{ steps.release.outputs.releases_created }}
                uses: ./.github/actions/install
                with:
                    node-version: ${{ env.NODE_VERSION }}

            -   name: Build
                if: ${{ steps.release.outputs.releases_created }}
                uses: ./.github/actions/build

            -   name: Publish
                if: ${{ steps.release.outputs.releases_created }}
                run: npx lerna publish from-package --yes
                env:
                    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            -   uses: tada5hi/action-docker-image-publish@v3
                if: ${{ steps.release.outputs.releases_created }}
                with:
                    cleanup: false
                    registryRepository: authup/authup
                    registryTag: |
                        latest
                        ${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}

            -   uses: tada5hi/action-docker-image-publish@v3
                if: ${{ steps.release.outputs.releases_created }}
                with:
                    registryHost: docker.io
                    registryRepository: authup/authup
                    registryUser: authup
                    registryTag: |
                        latest
                        ${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}
                    registryPassword: ${{ secrets.DOCKER_HUB_TOKEN }}
