name: Release

on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      pull-requests: write
    steps:
      -   name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

      -   name: Install
          uses: ./.github/actions/install
          with:
            node-version: ${{ env.NODE_VERSION }}
            node-registry: ${{ env.NODE_REGISTRY }}

      -   name: Build
          uses: ./.github/actions/build

      -   name: Create Release Pull Request or Publish to npm
          id: changesets
          uses: changesets/action@v1
          with:
            publish: npm run release
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      -   uses: tada5hi/action-docker-image-publish@master
          if: steps.changesets.outputs.published == 'true'
          with:
            cache: true
            registryRepository: authup
            registryTag: latest

      -   uses: tada5hi/action-docker-image-publish@master
          if: steps.changesets.outputs.published == 'true'
          with:
            registryHost: docker.io
            registryProject: authup
            registryRepository: authup
            registryUser: authup
            registryTag: latest
            registryPassword: ${{ secrets.DOCKER_HUB_TOKEN }}
